version: '3'
services:
  server:
    image: clickhouse/clickhouse-server
    restart: unless-stopped
    ports:
     - "8123:8123" #HTTP API Port for http requests. used by JDBC, ODBC and web interfaces.
     - "9000:9000"
     - "9009:9009"
     #https://clickhouse.com/docs/en/guides/sre/network-ports
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - "./datadir:/var/lib/clickhouse/:rw"
      # - "./datadir-log:/var/log/clickhouse-server"
      # - "./config.xml:/etc/clickhouse-server/config.d/sentry.xml"
      #
    environment:
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_DB: "analytics"
      CLICKHOUSE_USER: "metin"
      CLICKHOUSE_PASSWORD: "metin123.$"
      # You might want to change this to a higher value (and ensure your host has enough memory)
      # MAX_MEMORY_USAGE_RATIO: 0.3
    healthcheck:
      test: [
          "CMD-SHELL",
          # Manually override any http_proxy envvar that might be set, because
          # this wget does not support no_proxy. See:
          # https://github.com/getsentry/self-hosted/issues/1537
          "http_proxy='' wget -nv -t1 --spider 'http://localhost:8123/' || exit 1",
        ]
      interval: 10s
      timeout: 10s
      retries: 30

  client:
    image: clickhouse/clickhouse-client
    entrypoint:
      - /bin/sleep
    command:
      - infinity
