version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper

  kafka-1:
    image: wurstmeister/kafka
    depends_on: [zookeeper]
    ports:
    - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${DOCKER_HOST_IP:-192.168.10.11}:9092,PLAINTEXT_INTERNAL://kafka-1:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.10.11:9092,PLAINTEXT_INTERNAL://kafka-1:29092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_DEFAULT_REPLICATION_FACTOR: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
  kafka-2:
    image: wurstmeister/kafka
    ports:
    - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 2  # unique
      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${DOCKER_HOST_IP:-192.168.10.11}:9093,PLAINTEXT_INTERNAL://kafka-2:29093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.10.11:9093,PLAINTEXT_INTERNAL://kafka-2:29093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093,PLAINTEXT_INTERNAL://:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_DEFAULT_REPLICATION_FACTOR: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
      KAFKA_CREATE_TOPICS: "dmpAPI:2:2,sentiment:2:2"
    depends_on:  # ensure this joins the other
    - zookeeper
    - kafka-1

# kubectl -n kafka exec -ti kafka-1-576fdbbdf4-r8s57 bash
# docker exec -it kafka_kafka-1_1 bash
# opt/kafka/bin/kafka-topics.sh --create --zookeeper zookeeper:2181 --replication-factor 2 --partitions 2 --topic dmpAPI
# opt/kafka/bin/kafka-topics.sh --create --zookeeper zookeeper:2181 --replication-factor 2 --partitions 2 --topic sentiment

# opt/kafka/bin/kafka-topics.sh --zookeeper zookeeper:2181 --alter --topic dmpAPI --partitions 2
# opt/kafka/bin/kafka-topics.sh --zookeeper zookeeper:2181 --alter --topic sentiment --partitions 2

# opt/kafka/bin/kafka-topics.sh --describe --zookeeper zookeeper:2181 --topic sentiment