apiVersion: v1
kind: Service
metadata:
  name: kafka-2-service
spec:
  selector:
    app: kafka-2
  ports:
  - port: 9093
    targetPort: 9093
    nodePort: 30093
    protocol: TCP
    name: http
  type: LoadBalancer

