apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-1
  template:
    metadata:
      labels:
        app: kafka-1
    spec:
      hostNetwork: true   
      containers:
        - env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: KUBE_CLUSTER_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP          
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://$(MY_POD_IP):9092,PLAINTEXT_INTERNAL://$(KUBE_CLUSTER_IP):29092
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_DEFAULT_REPLICATION_FACTOR
              value: "2"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: PLAINTEXT_INTERNAL
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://:9092,PLAINTEXT_INTERNAL://:29092
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "2"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "2"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "$(KUBE_CLUSTER_IP):30181"
          image: wurstmeister/kafka
          name: kafka-1
          ports:
            - containerPort: 9092
      restartPolicy: Always
      # nodeSelector:
      #   type: master

# docker exec -it kafka_kafka-1_1 bash
# opt/kafka/bin/kafka-topics.sh --create --zookeeper zookeeper:2181 --replication-factor 2 --partitions 2 --topic dmpAPI
# opt/kafka/bin/kafka-topics.sh --create --zookeeper zookeeper:2181 --replication-factor 2 --partitions 2 --topic sentiment

# opt/kafka/bin/kafka-topics.sh --zookeeper zookeeper:2181 --alter --topic dmpAPI --partitions 2
# opt/kafka/bin/kafka-topics.sh --zookeeper zookeeper:2181 --alter --topic sentiment --partitions 2

# --------------------------------
# kubectl exec -it kafka-1-54695884cf-sxlh5 bash -n kafka

# opt/kafka/bin/kafka-topics.sh --create --zookeeper 192.168.10.11:30181 --replication-factor 2 --partitions 2 --topic dmpAPI
# opt/kafka/bin/kafka-topics.sh --create --zookeeper 192.168.10.11:30181 --replication-factor 2 --partitions 2 --topic sentiment

# opt/kafka/bin/kafka-topics.sh --zookeeper 192.168.10.11:30181 --alter --topic dmpAPI --partitions 2
# opt/kafka/bin/kafka-topics.sh --zookeeper 192.168.10.11:30181 --alter --topic sentiment --partitions 2