apiVersion: v1
kind: Service
metadata:
  name: kafka-1-service
spec:
  selector:
    app: kafka-1
  ports:
  - port: 9092
    targetPort: 9092
    nodePort: 30092
    protocol: TCP
    name: http
  type: LoadBalancer

